### PR TITLE
can loop

### PR DESCRIPTION
**Pull request by tossp**
Add a attribute `rnCarouselControlsCanLoop`

### CODE REVIEW

**Comment by revolunet** [comment]
nice, thanks, can you please add to the info to the README too ?

**Comment by tossp** [comment]
I'm sorry,  my English is poor.so I don't write complicated sentences. T_T

use: translate.google.cn

**Comment by revolunet** [comment]
Ok. i'll do the README update.

I think the naming "can loop" is confusing because it applies only to the prev/next controls, not the swipe itself.

Could you please rename to "rnCarouselControlsAllowLoop" ?

**Comment by tossp** [comment]
Well, it has been completed

**Comment by tossp** [comment]
Do you think behind this improvement needs?

**Comment by revolunet** [comment]
looks good to me thanks :)

the final step would be to rebase your 5 commits in a single one
 -  make a backup : `git branch backup`
 -  `git rebase HEAD~6` "fixup" the commits until the first one
 -  write the single commit message
if all is ok then you can push --force

thanks !

**Comment by tossp** [comment]
Complete rebase

**Comment by revolunet** [comment]
that's great, thanks man !

**Comment by Srinix** [comment]
When I'm in last slide the next arrow is disappeared and when first slide the prev arrow is getting removed.
If I'm not wrong, Infinite loop should have both the arrows if the slides are more than 0.

**Pull request merged**
