### PR TITLE
rn-swipe-disabled =true will only disable swipe events

### PR DESCRIPTION
**Pull request by mauricio-delaquintana-tierconnect-com**
rn-swipe-disabled =true will only disable swipe events

### CODE REVIEW

**Comment by nadyav** [comment]
Looks good to me.

**Comment by gulsahkandemir** [comment]
lgtm, too. This is exactly what we needed.

**Comment by nadyav** [comment]
Could someone with write access please review and merge this PR? It's a highly desirable feature, so would be awesome if it finally gets released. Thanks!

**Comment by sonicd300** [comment]
+1

**Comment by revolunet** [comment]
sorry all for the delay. btw, this project is looking for maintainers if you're interested, just ping me

**Comment by gulsahkandemir** [comment]
This change should have been made in src/directives/rn-carousel.js file instead of dist/angular-carousel.js file.

Now it's not included in the latest release 0.3.11.

**Comment by revolunet** [comment]
sorry just repushed 0.3.12 with the fix

**Comment by gulsahkandemir** [comment]
thanks a lot!

**Pull request merged**
