### PR TITLE
End to End Swiping & Set of images

### PR DESCRIPTION
**Pull request by big-data-labs**
added demo at the end of the index.html

### CODE REVIEW

**Comment by revolunet** [comment]
Thanks.
Cant you use `scope[iAttributes.rnCarouselOnInfiniteScrollRight]()` instead of `eval("scope." + iAttributes.rnCarouselOnInfiniteScrollRight)` ?

Or even better, use `$parse(iAttributes.rnCarouselOnInfiniteScrollRight)(scope)` ?

**Comment by revolunet** [comment]
also please remove the console.log

**Comment by revolunet** [comment]
thanks and sorry for the delay

**Comment by big-data-labs** [comment]
Thanks!  Any thoughts on when an Angular 2 version of the carousel will be
created?

We ended up shifting over to jQuery Slick Carousel:

http://kenwheeler.github.io/slick/

**Comment by revolunet** [comment]
i won't be able to work on this but i hope some contributors will :)

**Comment by revolunet** [comment]
and yes, slick is awesome

**Comment by big-data-labs** [comment]
Did you see that we also created a demo at the end of the page. It's not
showing at : http://blog.revolunet.com/angular-carousel/

**Comment by revolunet** [comment]
sorry, done, thanks

**Pull request merged**
